# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2019-07-20 19:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Information',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Iname', models.CharField(max_length=100)),
                ('Imob', models.IntegerField()),
                ('Imail', models.EmailField(max_length=254)),
                ('Iadhar', models.IntegerField()),
                ('Isalary', models.IntegerField()),
            ],
        ),
    ]
