# Generated by Django 2.2.3 on 2020-01-14 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('information', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='information',
            name='Imob',
            field=models.IntegerField(max_length=10),
        ),
    ]
